"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ArrowUpRight, ArrowDownRight, Wallet, TrendingUp, AlertTriangle, Activity } from "lucide-react";

export default function DashboardOverview() {
  const [summary, setSummary] = useState<any>(null);
  const [opportunities, setOpportunities] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const [portfolioData, oppsData] = await Promise.all([
          api.getPortfolioSummary(),
          api.getOpportunities()
        ]);
        setSummary(portfolioData);
        setOpportunities(oppsData.slice(0, 5)); // Just recent 5
      } catch (err) {
        console.error("Failed to load dashboard data", err);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  if (loading) {
    return <div className="flex h-full items-center justify-center">Loading dashboard...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">MARKET 2.0</h2>
          <p className="text-muted-foreground">
            Your portfolio performance and latest market opportunities.
          </p>
        </div>
        <div className="flex space-x-2">
            <Badge variant="outline" className="border-blue-500 text-blue-500 bg-blue-500/10 px-3 py-1 font-bold">
                EXECUTION: PAPER ONLY
            </Badge>
            <Badge variant="outline" className="border-red-500 text-red-500 bg-red-500/10 px-3 py-1 font-bold">
                LIVE: LOCKED
            </Badge>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Portfolio Value</CardTitle>
            <Wallet className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              ${summary?.total_value?.toLocaleString(undefined, { minimumFractionDigits: 2 })}
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              {summary?.total_pnl >= 0 ? "+" : ""}{summary?.total_pnl?.toLocaleString(undefined, { minimumFractionDigits: 2 })} All Time
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Open Positions</CardTitle>
            <Activity className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{summary?.open_positions || 0}</div>
            <p className="text-xs text-muted-foreground mt-1">
              Active trades in virtual portfolio
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Exposure</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {(summary?.exposure_pct || 0).toFixed(1)}%
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              Capital currently deployed
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Max Drawdown</CardTitle>
            <AlertTriangle className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-destructive">
              -{(summary?.max_drawdown * 100 || 0).toFixed(2)}%
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              Historical maximum drawdown
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-7">
        <Card className="col-span-4">
          <CardHeader>
            <CardTitle>Recent Opportunities</CardTitle>
            <CardDescription>Latest trade signals generated by the intelligence engine.</CardDescription>
          </CardHeader>
          <CardContent>
            {opportunities.length === 0 ? (
              <div className="text-center py-4 text-muted-foreground">No recent opportunities</div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Symbol</TableHead>
                    <TableHead>Direction</TableHead>
                    <TableHead>Confidence</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="text-right">Risk</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {opportunities.map((opp) => (
                    <TableRow key={opp.opportunity_id}>
                      <TableCell className="font-medium">{opp.symbol}</TableCell>
                      <TableCell>
                        <div className="flex items-center">
                          {opp.direction === "BUY" ? (
                            <ArrowUpRight className="mr-1 h-4 w-4 text-green-500" />
                          ) : opp.direction === "SELL" ? (
                            <ArrowDownRight className="mr-1 h-4 w-4 text-red-500" />
                          ) : null}
                          <span className={opp.direction === "BUY" ? "text-green-500 font-bold" : opp.direction === "SELL" ? "text-red-500 font-bold" : ""}>
                            {opp.direction}
                          </span>
                        </div>
                      </TableCell>
                      <TableCell>{(opp.confidence_score * 100).toFixed(0)}%</TableCell>
                      <TableCell>
                        <Badge variant="outline" className={
                          opp.status === "AWAITING_APPROVAL" ? "border-yellow-500 text-yellow-500" :
                          opp.status === "EXECUTED" ? "border-green-500 text-green-500" : ""
                        }>
                          {opp.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right">{opp.risk_level}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>

        <Card className="col-span-3">
          <CardHeader>
            <CardTitle>Market Regime</CardTitle>
            <CardDescription>Current AI assessment of market conditions.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">Overall Trend</span>
                <Badge className="bg-green-500/10 text-green-500 hover:bg-green-500/20 border-green-500/20">Bullish</Badge>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">Volatility</span>
                <Badge variant="outline" className="text-yellow-500 border-yellow-500/20">Elevated</Badge>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">AI Confidence</span>
                <span className="text-sm font-bold">85%</span>
              </div>
              <div className="pt-4 border-t border-border mt-4">
                <p className="text-sm text-muted-foreground">
                  "Markets are showing strong upside momentum driven by positive macro developments. However, short-term indicators suggest mild overbought conditions."
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
