"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowUpRight, ArrowDownRight, CheckCircle, XCircle, Zap } from "lucide-react";

export default function SignalCenter() {
  const [opportunities, setOpportunities] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchOpportunities();
  }, []);

  const fetchOpportunities = async () => {
    try {
      const data = await api.getOpportunities();
      setOpportunities(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleAction = async (id: string, action: "approve" | "ignore") => {
    try {
      const currentPrice = 2450.0; // Mock current price for MVP
      if (action === "approve") {
        await api.approveOpportunity(id, currentPrice);
      } else {
        await api.ignoreOpportunity(id, currentPrice);
      }
      fetchOpportunities();
    } catch (err: any) {
      alert(err.response?.data?.detail || "Action failed");
      console.error(err);
    }
  };

  const handleGenerateMock = async () => {
    try {
      await api.generateMockOpportunity();
      fetchOpportunities();
    } catch (err) {
      console.error(err);
    }
  };

  if (loading) return <div className="flex h-full items-center justify-center">Loading signals...</div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Signal Center</h2>
          <p className="text-muted-foreground">
            Review and approve trade opportunities generated by the intelligence engine.
          </p>
        </div>
        <Button variant="outline" onClick={handleGenerateMock}>
          <Zap className="mr-2 h-4 w-4" />
          Generate Test Signal
        </Button>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {opportunities.length === 0 ? (
          <div className="col-span-full py-12 text-center text-muted-foreground bg-muted/20 border border-dashed rounded-lg">
            No active trade opportunities. Click "Generate Test Signal" to simulate one.
          </div>
        ) : (
          opportunities.map(opp => (
            <Card key={opp.opportunity_id} className="flex flex-col">
              <CardHeader className="pb-3 border-b border-border mb-3">
                <div className="flex justify-between items-start">
                  <div>
                    <CardTitle className="text-xl">{opp.symbol}</CardTitle>
                    <CardDescription className="mt-1">{new Date(opp.timestamp).toLocaleString()}</CardDescription>
                  </div>
                  <Badge variant="outline" className={
                    opp.status === "AWAITING_APPROVAL" ? "border-yellow-500 text-yellow-500 bg-yellow-500/10" :
                    opp.status === "EXECUTED" ? "border-green-500 text-green-500 bg-green-500/10" : 
                    opp.status === "REJECTED" ? "border-red-500 text-red-500 bg-red-500/10" : ""
                  }>
                    {opp.status}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="flex-1 space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-sm font-medium">Direction</span>
                  <div className="flex items-center">
                    {opp.direction === "BUY" ? (
                      <ArrowUpRight className="mr-1 h-5 w-5 text-green-500" />
                    ) : opp.direction === "SELL" ? (
                      <ArrowDownRight className="mr-1 h-5 w-5 text-red-500" />
                    ) : null}
                    <span className={`text-lg font-bold ${opp.direction === "BUY" ? "text-green-500" : opp.direction === "SELL" ? "text-red-500" : ""}`}>
                      {opp.direction}
                    </span>
                  </div>
                </div>

                <div className="flex justify-between items-center">
                  <span className="text-sm font-medium">Confidence Score</span>
                  <span className="font-mono">{(opp.confidence_score * 100).toFixed(1)}%</span>
                </div>

                <div className="flex justify-between items-center">
                  <span className="text-sm font-medium">Risk Level</span>
                  <Badge variant="outline">{opp.risk_level}</Badge>
                </div>

                {opp.strategy_evidence && (
                  <div className="pt-2 border-t border-border">
                    <p className="text-xs font-semibold mb-1 text-muted-foreground">STRATEGY EVIDENCE</p>
                    <div className="flex justify-between text-sm">
                      <span>{opp.strategy_evidence.strategy_name}</span>
                      <span className={opp.strategy_evidence.signal_direction === 1 ? "text-green-500" : "text-red-500"}>
                        {opp.strategy_evidence.signal_type} ({opp.strategy_evidence.signal_score.toFixed(1)})
                      </span>
                    </div>
                  </div>
                )}

                {opp.ai_evidence && (
                  <div className="pt-2 border-t border-border">
                    <p className="text-xs font-semibold mb-1 text-muted-foreground">AI EVIDENCE</p>
                    <div className="flex justify-between text-sm mb-1">
                      <span>Source: {opp.ai_evidence.provider_id === "MockAI" ? "MOCK" : "REAL"}</span>
                      <span className={opp.ai_evidence.direction === "BUY" ? "text-green-500" : "text-red-500"}>
                        {opp.ai_evidence.direction} ({opp.ai_evidence.ai_score.toFixed(1)})
                      </span>
                    </div>
                    <p className="text-xs text-muted-foreground italic line-clamp-2">
                      "{opp.ai_evidence.thesis || 'No reasoning provided'}"
                    </p>
                  </div>
                )}
                
                <div className="pt-2 border-t border-border flex justify-between text-xs text-muted-foreground">
                    <span>NEWS SOURCE: MOCK</span>
                    <span>DATA SOURCE: UPSTOX / MOCK</span>
                </div>
              </CardContent>

              {opp.status === "AWAITING_APPROVAL" && (
                <CardFooter className="flex gap-3 border-t border-border pt-4">
                  <Button 
                    variant="outline" 
                    className="w-full"
                    onClick={() => handleAction(opp.opportunity_id, "ignore")}
                  >
                    <XCircle className="mr-2 h-4 w-4" /> IGNORE
                  </Button>
                  <Button 
                    className="w-full bg-green-600 hover:bg-green-700 text-white"
                    onClick={() => handleAction(opp.opportunity_id, "approve")}
                  >
                    <CheckCircle className="mr-2 h-4 w-4" /> TAKE PAPER TRADE
                  </Button>
                </CardFooter>
              )}
            </Card>
          ))
        )}
      </div>
    </div>
  );
}
