import asyncio
import os
import sys
import pandas as pd
from datetime import datetime, timezone, timedelta
import logging

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from app.core.config import settings
from dotenv import load_dotenv
load_dotenv()

from app.data.database.session import SessionLocal
from app.data.providers.upstox_provider import UpstoxMarketDataProvider
from app.strategies.momentum.strategy import MomentumStrategy
from app.engine.signal import SignalEngine, HybridDecisionAggregator
from app.intelligence.ai_provider import MockAIProvider
from app.engine.risk import RiskEngine
from app.engine.workflow import WorkflowOrchestrator
from app.engine.portfolio import VirtualPortfolio
from app.analytics.service import AnalyticsService

logging.basicConfig(level=logging.INFO, format="%(levelname)s - %(message)s")

async def main():
    print("==================================================")
    print("PHASE 13 - PAPER TRADING OPERATIONS VALIDATION")
    print("==================================================")
    
    # 1. Start Session
    db = SessionLocal()
    analytics = AnalyticsService(db)
    
    active = analytics.get_current_session()
    if not active:
        session = analytics.start_session("Live Market Ops Session")
        print(f"Started new Paper Session: {session.id}")
    else:
        session = active
        print(f"Resuming existing Paper Session: {session.id}")
    
    # Check credentials
    if not os.getenv("UPSTOX_ANALYTICS_TOKEN"):
        print("BLOCKED - UPSTOX ANALYTICS TOKEN UNAVAILABLE")
        db.close()
        return
        
    print("MARKET DATA = REAL (UPSTOX)")
    print("NEWS = MOCK")
    print("FUNDAMENTALS = MOCK")
    print("AI = MOCK / SIMULATED")
    print("EXECUTION = PAPER")
    print("LIVE = LOCKED\n")
        
    provider = UpstoxMarketDataProvider()
    strategy = MomentumStrategy(sma_window=50, rsi_window=14, rsi_long_threshold=50, rsi_short_threshold=50)
    ai_provider = MockAIProvider()
    hybrid = HybridDecisionAggregator()
    risk_engine = RiskEngine()
    portfolio = VirtualPortfolio()
    portfolio.load_from_db(db)
    
    from app.engine.execution import PaperExecutionProvider
    execution_provider = PaperExecutionProvider(portfolio)
    # Using a dummy mock adapter since this is an offline validation script
    class MockNotificationAdapter:
        async def send_opportunity(self, opp): pass
        async def send_execution(self, order): pass
        async def send_error(self, error): pass
    notification_adapter = MockNotificationAdapter()
    
    orchestrator = WorkflowOrchestrator(
        risk_engine=risk_engine, 
        execution_provider=execution_provider, 
        notification_adapter=notification_adapter
    )
    
    watchlist = ["RELIANCE.NS", "TCS.NS"]
    
    end_date = datetime.now(timezone.utc)
    start_date = end_date - timedelta(days=5)
    
    signals_generated = 0
    risk_approved = 0
    executed = 0
    
    for symbol in watchlist:
        print(f"\n--- Processing {symbol} ---")
        try:
            df = provider.get_historical_ohlcv(symbol, "5m", start_date, end_date)
        except Exception as e:
            print(f"Error fetching data: {e}")
            continue
            
        if df.empty:
            print(f"No data for {symbol}.")
            continue
            
        # Fresh candle handling (Phase 11C preserved)
        current_time = datetime.now(timezone.utc)
        latest_ts = pd.Timestamp(df.iloc[-1]['timestamp'])
        if latest_ts.tzinfo is None:
            latest_ts = latest_ts.tz_localize('UTC')
            
        if current_time < latest_ts + timedelta(minutes=5):
            print(f"Candle at {latest_ts} is still forming. Dropping.")
            df = df.iloc[:-1]
            
        if df.empty:
            continue
            
        import app.quantitative.features.core as features
        df['SMA_50'] = features.calculate_sma(df, 50)
        df['RSI_14'] = features.calculate_rsi(df, 14)
        df = df.dropna()
        
        if df.empty:
            continue
            
        signals = strategy.generate_signals(df)
        if not signals:
            print("FLAT / NO SIGNAL generated by strategy.")
            continue
            
        latest_completed_ts = pd.Timestamp(df.iloc[-1]['timestamp'])
        latest_signal = signals[-1]
        
        if pd.Timestamp(latest_signal.timestamp) != latest_completed_ts:
            print(f"Latest completed candle at {latest_completed_ts} produced NO SIGNAL (Flat).")
            continue
            
        signals_generated += 1
        print(f"Generated FRESH {latest_signal.direction} signal at {latest_signal.timestamp}")
        
        signal_engine = SignalEngine()
        from app.engine.models import DecisionMode
        
        # We need Mock AI Analysis for create_opportunity
        from app.intelligence.models import AIAnalysis, MarketRegime
        ai_analysis = AIAnalysis(
            provider_id="MockAI",
            timestamp=datetime.now(timezone.utc),
            symbol=symbol,
            confidence=0.9 if latest_signal.direction == 1 else 0.8,
            market_context="Bullish trend expected.",
            thesis="Mock AI sees upside potential.",
            risks=[],
            raw_response="{}",
            evidence="",
            source="MOCK"
        )
        
        opp = signal_engine.create_opportunity(
            symbol=symbol,
            timestamp=latest_completed_ts.to_pydatetime().replace(tzinfo=timezone.utc),
            timeframe="5m",
            decision_mode=DecisionMode.HYBRID,
            strategy_signal=latest_signal,
            ai_analysis=ai_analysis
        )
        
        # Signal Engine already creates the opportunity and calculates hybrid_score
        # based on the provided strategy_signal and ai_analysis
        
        risk_result = risk_engine.evaluate(opp, portfolio.cash, [], datetime.now(timezone.utc))
        
        if not risk_result.approved:
            print(f"RISK REJECTED: {risk_result.reason}")
            # Ensure opportunity gets logged as REJECTED in DB for Funnel metrics
            from app.data.database.models import TradeOpportunityDB
            db_opp = TradeOpportunityDB(
                opportunity_id=opp.opportunity_id,
                session_id=session.id,
                symbol=opp.symbol,
                timestamp=opp.timestamp,
                decision_mode=opp.decision_mode.value,
                direction=opp.direction.value,
                confidence_score=opp.confidence_score,
                strategy_version=opp.strategy_version,
                ai_confidence=opp.ai_confidence,
                hybrid_score=opp.hybrid_score,
                market_regime=opp.market_regime,
                status="RISK_REJECTED",
                reasoning=[risk_result.reason]
            )
            db.add(db_opp)
            db.commit()
            continue
            
        risk_approved += 1
        print("RISK APPROVED. Forwarding to Human Orchestrator...")
        
        # Pass to orchestrator which will validate risk and status internally
        # We need to set status as CREATED to allow processing
        from app.engine.models import OpportunityStatus
        opp.status = OpportunityStatus.CREATED
        
        await orchestrator.process_new_opportunity(opp, df.iloc[-1]['close'], db)
        
        if opp.status == OpportunityStatus.AWAITING_APPROVAL:
            # Human approval simulation
            execution_order = await orchestrator.process_user_action(opp, "TAKE_TRADE", df.iloc[-1]['close'], db)
            if execution_order:
                executed += 1
                print(f"PAPER EXECUTION SUCCESS: {execution_order.order_id} at {execution_order.fill_price}")
                
                # Duplicate check
                print("Attempting duplicate execution...")
                dup_order = await orchestrator.process_user_action(opp, "TAKE_TRADE", df.iloc[-1]['close'], db)
                if dup_order is None:
                    print("DUPLICATE SUCCESSFULLY BLOCKED by idempotency engine.")
                else:
                    print("ERROR: Duplicate was not blocked!")
        else:
            print(f"Opportunity blocked at orchestrator: {opp.status.value}")
                
    # End of watchlist processing
    print("\n==================================================")
    print("SESSION REPORT")
    print(f"Signals Generated: {signals_generated}")
    print(f"Risk Approved:     {risk_approved}")
    print(f"Paper Executed:    {executed}")
    
    # Check Daily Report
    report = analytics.get_daily_report()
    print("\nDAILY REPORT METRICS:")
    for k, v in report.items():
        print(f"  {k}: {v}")
        
    print("\n==================================================")
    print("FINAL STATUS: PASS" if executed > 0 else "FINAL STATUS: PASS WITH LIMITATION (NO TRADES)")
    
    db.close()

if __name__ == "__main__":
    asyncio.run(main())
