from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional
from datetime import datetime
import pandas as pd

class BacktestConfig(BaseModel):
    """Configuration for a backtest run."""
    strategy_id: str = Field(..., description="ID of the strategy to run")
    strategy_parameters: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the strategy")
    symbol: str = Field(..., description="Symbol to backtest")
    initial_capital: float = Field(100000.0, description="Initial capital for the backtest")
    slippage_bps: float = Field(0.0, description="Slippage in basis points (1 bps = 0.01%)")
    fee_bps: float = Field(0.0, description="Transaction fee in basis points")

class Order(BaseModel):
    """A simulated order generated by the backtester."""
    id: str = Field(..., description="Unique order ID")
    symbol: str = Field(..., description="Instrument symbol")
    timestamp: datetime = Field(..., description="Time the order was generated")
    side: int = Field(..., description="1 for Buy, -1 for Sell, 0 for Close All")
    quantity: float = Field(0.0, description="Quantity to order. 0 means all available.")
    status: str = Field("PENDING", description="Status: PENDING, FILLED, REJECTED, CANCELED")
    strategy_id: str = Field(..., description="Strategy that generated the order")

class Trade(BaseModel):
    """A completed round-trip trade."""
    id: str = Field(..., description="Unique trade ID")
    symbol: str = Field(..., description="Instrument symbol")
    entry_timestamp: datetime = Field(...)
    exit_timestamp: datetime = Field(...)
    entry_price: float = Field(...)
    exit_price: float = Field(...)
    quantity: float = Field(...)
    side: int = Field(..., description="1 for Long, -1 for Short")
    fees: float = Field(0.0, description="Total fees paid for entry and exit")
    net_pnl: float = Field(..., description="Net Profit/Loss including fees")
    return_pct: float = Field(..., description="Percentage return of the trade")
    strategy_id: str = Field(...)

class Position(BaseModel):
    """Current open position state."""
    symbol: str
    quantity: float
    average_entry_price: float
    side: int  # 1 for Long, -1 for Short
    entry_timestamp: datetime

class BacktestResult(BaseModel):
    """Standardized output of a backtest."""
    config: BacktestConfig
    metrics: Dict[str, float] = Field(..., description="Performance metrics")
    trades: List[Trade] = Field(..., description="Ledger of completed trades")
    equity_curve: List[Dict[str, Any]] = Field(..., description="Daily equity values [{timestamp, equity, drawdown}]")
    
    class Config:
        arbitrary_types_allowed = True
