"""Add PaperExperimentDB

Revision ID: 02f9c861976a
Revises: 3b869bc6cfba
Create Date: 2026-08-18 16:14:20.988817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f9c861976a'
down_revision: Union[str, Sequence[str], None] = '3b869bc6cfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_experiments',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_capital', sa.Float(), nullable=False),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('data_provider', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('watchlist', sa.JSON(), nullable=False),
    sa.Column('strategies', sa.JSON(), nullable=False),
    sa.Column('decision_modes', sa.JSON(), nullable=False),
    sa.Column('risk_configuration', sa.JSON(), nullable=False),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_index(op.f('ix_paper_experiments_experiment_id'), 'paper_experiments', ['experiment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_experiments_experiment_id'), table_name='paper_experiments')
    op.drop_table('paper_experiments')
    # ### end Alembic commands ###
