"""Add PaperTradingSessionDB and session_id

Revision ID: 0678c5e477b2
Revises: 5992b25fbe73
Create Date: 2026-08-17 18:39:32.136051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0678c5e477b2'
down_revision: Union[str, Sequence[str], None] = '5992b25fbe73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('starting_capital', sa.Float(), nullable=False),
    sa.Column('current_capital', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_sessions_id'), 'paper_sessions', ['id'], unique=False)
    op.add_column('paper_trading_journal', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_paper_trading_journal_session_id'), 'paper_trading_journal', ['session_id'], unique=False)
    op.create_foreign_key(None, 'paper_trading_journal', 'paper_sessions', ['session_id'], ['id'])
    op.add_column('trade_opportunities', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_trade_opportunities_session_id'), 'trade_opportunities', ['session_id'], unique=False)
    op.create_foreign_key(None, 'trade_opportunities', 'paper_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade_opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_trade_opportunities_session_id'), table_name='trade_opportunities')
    op.drop_column('trade_opportunities', 'session_id')
    op.drop_constraint(None, 'paper_trading_journal', type_='foreignkey')
    op.drop_index(op.f('ix_paper_trading_journal_session_id'), table_name='paper_trading_journal')
    op.drop_column('paper_trading_journal', 'session_id')
    op.drop_index(op.f('ix_paper_sessions_id'), table_name='paper_sessions')
    op.drop_table('paper_sessions')
    # ### end Alembic commands ###
