"""Phase 14 Operations Tables

Revision ID: 3b869bc6cfba
Revises: 6c4472879d35
Create Date: 2026-08-18 15:57:51.932990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b869bc6cfba'
down_revision: Union[str, Sequence[str], None] = '6c4472879d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_processed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_market_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_strategy_eval', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opportunity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_risk_eval', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_paper_execution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_session', sa.String(), nullable=True),
    sa.Column('provider_status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeats_id'), 'heartbeats', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_category'), 'incidents', ['category'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_instrument'), 'incidents', ['instrument'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_timestamp'), 'incidents', ['timestamp'], unique=False)
    op.create_table('market_health',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('latest_candle_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_completed_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_age_seconds', sa.Float(), nullable=True),
    sa.Column('expected_interval_seconds', sa.Float(), nullable=True),
    sa.Column('candles_received', sa.BigInteger(), nullable=True),
    sa.Column('missing_candles', sa.BigInteger(), nullable=True),
    sa.Column('duplicate_candles', sa.BigInteger(), nullable=True),
    sa.Column('invalid_candles', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_market_health_symbol'), 'market_health', ['symbol'], unique=False)
    op.create_table('provider_health',
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('success_count', sa.BigInteger(), nullable=True),
    sa.Column('error_429_count', sa.BigInteger(), nullable=True),
    sa.Column('timeout_count', sa.BigInteger(), nullable=True),
    sa.Column('auth_error_count', sa.BigInteger(), nullable=True),
    sa.Column('empty_response_count', sa.BigInteger(), nullable=True),
    sa.Column('malformed_response_count', sa.BigInteger(), nullable=True),
    sa.Column('connection_error_count', sa.BigInteger(), nullable=True),
    sa.Column('last_successful_request', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index(op.f('ix_provider_health_provider_id'), 'provider_health', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_health_provider_id'), table_name='provider_health')
    op.drop_table('provider_health')
    op.drop_index(op.f('ix_market_health_symbol'), table_name='market_health')
    op.drop_table('market_health')
    op.drop_index(op.f('ix_incidents_timestamp'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_instrument'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_category'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_heartbeats_id'), table_name='heartbeats')
    op.drop_table('heartbeats')
    # ### end Alembic commands ###
