"""phase12_models

Revision ID: 5992b25fbe73
Revises: aee8e0459f1b
Create Date: 2026-08-17 18:03:25.742370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5992b25fbe73'
down_revision: Union[str, Sequence[str], None] = 'aee8e0459f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trading_journal',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('strategy_version', sa.String(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('hybrid_score', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trading_journal_id'), 'paper_trading_journal', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trading_journal_opportunity_id'), 'paper_trading_journal', ['opportunity_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_table('watchlist_instruments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_instruments_id'), 'watchlist_instruments', ['id'], unique=False)
    op.add_column('trade_opportunities', sa.Column('strategy_version', sa.String(), nullable=True))
    op.add_column('trade_opportunities', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('trade_opportunities', sa.Column('hybrid_score', sa.Float(), nullable=True))
    op.add_column('trade_opportunities', sa.Column('market_regime', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_opportunities', 'market_regime')
    op.drop_column('trade_opportunities', 'hybrid_score')
    op.drop_column('trade_opportunities', 'ai_confidence')
    op.drop_column('trade_opportunities', 'strategy_version')
    op.drop_index(op.f('ix_watchlist_instruments_id'), table_name='watchlist_instruments')
    op.drop_table('watchlist_instruments')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_paper_trading_journal_opportunity_id'), table_name='paper_trading_journal')
    op.drop_index(op.f('ix_paper_trading_journal_id'), table_name='paper_trading_journal')
    op.drop_table('paper_trading_journal')
    # ### end Alembic commands ###
