"""Phase 5 engine models

Revision ID: 5e636725373c
Revises: b3819ce12fd8
Create Date: 2026-08-15 17:04:53.866994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e636725373c'
down_revision: Union[str, Sequence[str], None] = 'b3819ce12fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_table('instruments',
    # sa.Column('symbol', sa.String(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('exchange', sa.String(), nullable=False),
    # sa.Column('active', sa.Boolean(), nullable=True),
    # sa.PrimaryKeyConstraint('symbol')
    # )
    # op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    # op.create_table('ohlcv_data',
    # sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    # sa.Column('symbol', sa.String(), nullable=False),
    # sa.Column('open', sa.Float(), nullable=False),
    # sa.Column('high', sa.Float(), nullable=False),
    # sa.Column('low', sa.Float(), nullable=False),
    # sa.Column('close', sa.Float(), nullable=False),
    # sa.Column('volume', sa.BigInteger(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.PrimaryKeyConstraint('timestamp', 'symbol')
    # )
    # op.create_index(op.f('ix_ohlcv_data_symbol'), 'ohlcv_data', ['symbol'], unique=False)
    # op.create_index(op.f('ix_ohlcv_data_timestamp'), 'ohlcv_data', ['timestamp'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_positions_id'), 'paper_positions', ['id'], unique=False)
    op.create_index(op.f('ix_paper_positions_instrument_id'), 'paper_positions', ['instrument_id'], unique=False)
    op.create_table('trade_opportunities',
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision_mode', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('strategy_evidence', sa.JSON(), nullable=True),
    sa.Column('ai_evidence', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.create_index(op.f('ix_trade_opportunities_opportunity_id'), 'trade_opportunities', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_trade_opportunities_symbol'), 'trade_opportunities', ['symbol'], unique=False)
    op.create_table('paper_orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=True),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['trade_opportunities.opportunity_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_paper_orders_order_id'), 'paper_orders', ['order_id'], unique=False)
    op.create_table('user_decisions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['trade_opportunities.opportunity_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_user_decisions_action_id'), 'user_decisions', ['action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_decisions_action_id'), table_name='user_decisions')
    op.drop_table('user_decisions')
    op.drop_index(op.f('ix_paper_orders_order_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_trade_opportunities_symbol'), table_name='trade_opportunities')
    op.drop_index(op.f('ix_trade_opportunities_opportunity_id'), table_name='trade_opportunities')
    op.drop_table('trade_opportunities')
    op.drop_index(op.f('ix_paper_positions_instrument_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_ohlcv_data_timestamp'), table_name='ohlcv_data')
    op.drop_index(op.f('ix_ohlcv_data_symbol'), table_name='ohlcv_data')
    op.drop_table('ohlcv_data')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
