"""Add phase 13 journal fields

Revision ID: 6c4472879d35
Revises: b02151569d8b
Create Date: 2026-08-18 12:02:15.019736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4472879d35'
down_revision: Union[str, Sequence[str], None] = 'b02151569d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_trading_journal', sa.Column('decision_mode', sa.String(), nullable=True))
    op.add_column('paper_trading_journal', sa.Column('fees', sa.Float(), nullable=True))
    op.add_column('paper_trading_journal', sa.Column('slippage', sa.Float(), nullable=True))
    op.add_column('paper_trading_journal', sa.Column('data_source', sa.String(), nullable=True))
    op.add_column('paper_trading_journal', sa.Column('ai_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_trading_journal', 'ai_source')
    op.drop_column('paper_trading_journal', 'data_source')
    op.drop_column('paper_trading_journal', 'slippage')
    op.drop_column('paper_trading_journal', 'fees')
    op.drop_column('paper_trading_journal', 'decision_mode')
    # ### end Alembic commands ###
