"""phase_7_persistence

Revision ID: 6ed045a79fe6
Revises: 5e636725373c
Create Date: 2026-08-15 18:07:18.330628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed045a79fe6'
down_revision: Union[str, Sequence[str], None] = '5e636725373c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_keys_idempotency_key'), 'idempotency_keys', ['idempotency_key'], unique=False)
    op.create_table('portfolio_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_state_id'), 'portfolio_state', ['id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_decisions_action_id'), table_name='user_decisions')
    op.drop_table('user_decisions')
    op.drop_index(op.f('ix_paper_orders_order_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_trade_opportunities_symbol'), table_name='trade_opportunities')
    op.drop_index(op.f('ix_trade_opportunities_opportunity_id'), table_name='trade_opportunities')
    op.drop_table('trade_opportunities')
    op.drop_index(op.f('ix_portfolio_state_id'), table_name='portfolio_state')
    op.drop_table('portfolio_state')
    op.drop_index(op.f('ix_paper_positions_instrument_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_ohlcv_data_timestamp'), table_name='ohlcv_data')
    op.drop_index(op.f('ix_ohlcv_data_symbol'), table_name='ohlcv_data')
    op.drop_table('ohlcv_data')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_idempotency_keys_idempotency_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
