"""Add timeframe to OHLCVData

Revision ID: aee8e0459f1b
Revises: 6ed045a79fe6
Create Date: 2026-08-15 23:13:25.657664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee8e0459f1b'
down_revision: Union[str, Sequence[str], None] = '6ed045a79fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlcv_data', sa.Column('timeframe', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohlcv_data', 'timeframe')
    # ### end Alembic commands ###
