"""Add reasoning to TradeOpportunityDB

Revision ID: b02151569d8b
Revises: 0678c5e477b2
Create Date: 2026-08-17 18:47:30.788895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02151569d8b'
down_revision: Union[str, Sequence[str], None] = '0678c5e477b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_opportunities', sa.Column('reasoning', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_opportunities', 'reasoning')
    # ### end Alembic commands ###
